export interface ExperienceItem {
  id: string;
  title: string;
  date?: string;
  developer?: string;
  description: string;
  image: string;
  tags: string[];
  link?: string;
  score?: string;
  playtime?: string;
  review?: string;
}

export const travelData: ExperienceItem[] = [
    {
      id: "t1",
      title: "2026 東京自由行",
      date: "2026.01.14",
      description: "想把去過的地方、當時拍下來的畫面，以及值得留下來的小片段慢慢整理起來。這次去了很多非觀光客的秘境。",
      image: "/images/experience/travel/travel-cover.jpg", // 請換成你的真實照片
      tags: ["Travel", "Kyoto", "Photo"],
      link: "/experience/travel/kyoto-2026", // 獨立網頁的路由
    },
    {
      id: "t2",
      title: "環島機車旅行紀錄",
      date: "2022.7",
      description: "騎著 Jet 繞了一圈，沿途的海風與山景，還有那些路上遇到的人事物。",
      image: "/images/experience/travel/LINE_ALBUM_熱到靠北的環島_260417_1.jpg", 
      tags: ["Roadtrip", "Motorcycle", "Memory"],
      link: "/experience/travel/taiwan-roadtrip",
    }
];

export const galgameData: ExperienceItem[] = [
  {
    id: "g1",
    title: "さくら、もゆ",
    developer: "Favorite",
    description: "收錄玩過的作品、喜歡的題材、角色與劇情，以及那些真的有留下印象的內容。",
    image: "images/experience/gal/さくら、もゆ/KURO_e108b.png",
    tags: ["Sad", "Masterpiece"],
    score: "9.8 / 10",
    playtime: "132 小時",
    review: "我第一款玩到破防的gal，劇情反轉反轉再反轉，伏筆很多回饋感很強烈，加上BGM我只能說是真的有料",
  },
  {
    id: "g2",
    title: "星空鉄道とシロの旅",
    developer: "しらたまこ",
    description: "收錄玩過的作品、喜歡的題材、角色與劇情，以及那些真的有留下印象的內容。",
    image: "images/experience/gal/星空鉄道とシロの旅/galgame-cover.jpg",
    tags: ["Sad", "Short", "Masterpiece"],
    score: "9.7 / 10",
    playtime: "17 小時",
    review: "這部劇情不多，但結尾反轉是真想不到，小小的作品卻有很深的感悟",
  },
  {
    id: "g3",
    title: "桜の詩と刻",
    developer: "枕",
    description: "收錄玩過的作品、喜歡的題材、角色與劇情，以及那些真的有留下印象的內容。",
    image: "images/experience/gal/桜の詩と刻/藍.png",
    tags: ["Sad", "Literature", "Masterpiece"],
    score: "9.8 / 10",
    playtime: "212 小時",
    review: "純純的文學作品，真的讓我學到很多中世紀的文學作品，伏筆也是寫得很好，後面收尾也很不錯",
  },
  {
    id: "g4",
    title: "ATRI-MyDearMoments",
    developer: "FrontWing、枕",
    description: "收錄玩過的作品、喜歡的題材、角色與劇情，以及那些真的有留下印象的內容。",
    image: "images/experience/gal/atri/dump_frames0000010188.png",
    tags: ["Sad", "Short", "Masterpiece"],
    score: "10 / 10",
    playtime: "14 小時",
    review: "最推薦作品，敘述著人機愛情，也是我的啟蒙作，若是AI有了感情，你會怎麼看待他呢?",
  },
  {
    id: "g5",
    title: "9-nine-",
    developer: "ぱれっと",
    description: "",
    image: "images/experience/gal/9nine/cover.png",
    tags: ["Moe", "Music", "Mystery"],
    score: "8.1 / 10",
    playtime: "47 小時",
    review: "中規中矩，劇情結尾不算差，但拆分賣屬實有點貴了",
  },
  {
    id: "g6",
    title: "Summer Pockets",
    developer: "Key",
    description: "",
    image: "images/experience/gal/Summer Pockets/cover.png",
    tags: ["Sad", "Summer"],
    score: "8.8 / 10",
    playtime: "93 小時",
    review: "我第一款gal，全年齡向但劇情還是蠻感人的，算是很推薦的入門作",
  },
  {
    id: "g7",
    title: "アストラエアの白き永遠",
    developer: "FAVORITE",
    description: "",
    image: "images/experience/gal/アストラエアの白き永遠/cover.png",
    tags: ["Sad", "Fantasy"],
    score: "9.3 / 10",
    playtime: "143 小時",
    review: "介在廢萌/催淚之間，氛圍感很到位，人物描寫也很不錯，算很不錯的作品了",
  },
  {
    id: "g8",
    title: "星空のメモリア",
    developer: "FAVORITE",
    description: "",
    image: "images/experience/gal/星空のメモリア/cover.png",
    tags: ["Sad", "Starry Sky"],
    score: "9.2 / 10",
    playtime: "124 小時",
    review: "雖然有點老套，但劇情還是很不錯的，描述星空的部分也是相當有意境",
  },
  {
    id: "g9",
    title: "初雪櫻",
    developer: "SAGA PLANETS",
    description: "",
    image: "images/experience/gal/hatsuyuki/cover.png",
    tags: ["Sad", "Winter"],
    score: "7.7 / 10",
    playtime: "65 小時",
    review: "這不好說，我覺得男主人設屬實有點糟，結尾收的也很普，高開走低作",
  },
  {
    id: "g10",
    title: "さくらの雲＊スカアレットの恋",
    developer: "きゃべつそふと",
    description: "",
    image: "images/experience/gal/さくらの雲＊スカアレットの恋/cover.png",
    tags: ["Mystery", "Romance"],
    score: "9.4 / 10",
    playtime: "49 小時",
    review: "這部也很不錯，中上的推理作品，只是沒想到真女主是Bad End，但結尾還是收得很不錯的",
  },
  {
    id: "g11",
    title: "いろとりどりのセカイ",
    developer: "FAVORITE",
    description: "",
    image: "images/experience/gal/いろとりどりのセカイ/cover.png",
    tags: ["Sad", "Fantasy"],
    score: "8.9 / 10",
    playtime: "77 小時",
    review: "這部一言難盡，幾乎是去看真紅的，敘事方式跟櫻花萌放類似，但略為遜色，此外男主超自私",
  },
  {
    id: "g12",
    title: "枯れない世界と終わる花",
    developer: "SWEET&TEA",
    description: "",
    image: "images/experience/gal/枯れない世界と終わる花/cover.png",
    tags: ["Short", "Sad", "Fantasy"],
    score: "8.5 / 10",
    playtime: "33 小時",
    review: "中規中矩，雖然劇情算是蠻新盈的只是沒有把氛圍寫得很好，有點可惜的作品",
  },
  {
    id: "g13",
    title: "蒼の彼方のフォーリズム",
    developer: "sprite",
    description: "",
    image: "images/experience/gal/蒼の彼方のフォーリズム/cover.png",
    tags: ["Moe", "Sports"],
    score: "9.0 / 10",
    playtime: "73 小時",
    review: "非常適合推坑的作品，輕鬆平常且題材很特殊",
  },
  {
    id: "g14",
    title: "サノバウィッチ",
    developer: "ゆずソフト",
    description: "",
    image: "images/experience/gal/サノバウィッチ/cover.png",
    tags: ["Moe", "School", "Romance"],
    score: "8.4 / 10",
    playtime: "88 小時",
    review: "柚子社的廢萌作不多說， Ciallo～ (∠・ω< )⌒★",
  },
  {
    id: "g15",
    title: "千恋＊万花",
    developer: "ゆずソフト",
    description: "",
    image: "images/experience/gal/千恋＊万花/cover.png",
    tags: ["Moe", "Romance"],
    score: "9.1 / 10",
    playtime: "96 小時",
    review: "柚子社的經典之作，我想這應該快炙人口了，也是很經典的作品",
  },
  {
    id: "g16",
    title: "恋×シンアイ彼女",
    developer: "Us:track",
    description: "",
    image: "images/experience/gal/恋×シンアイ彼女/cover.png",
    tags: ["Moe", "Romance", "School"],
    score: "8.0 / 10",
    playtime: "39 小時",
    review: "壞女人!!!",
  },
  {
    id: "g17",
    title: "糖調！",
    developer: "ねこねこソフト",
    description: "",
    image: "images/experience/gal/糖調！/cover.png",
    tags: ["Moe", "Sweet", "Romance"],
    score: "9.2 / 10",
    playtime: "28 小時",
    review: "廢萌番，冰織真的好可愛!!",
  },
];

export const generalGameData: ExperienceItem[] = [
  {
    id: "gm1",
    title: "星穹鐵道",
    developer: "a",
    description: "a",
    image: "/images/category-projects.jpg", 
    tags: ["Open World", "Switch"],
    score: "10 / 10",
    playtime: "150+ 小時",
    review: ""
  },
];